language: generic
services:
  - docker
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - VERBOSE_OUTPUT=true
    - export PYTHONPATH=$PWD/ros_opcua_impl_python_opcua/python-opcua:$PYTHONPATH
    - ADDITIONAL_DEBS="libxml2-dev libmbedtls-dev"
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="noetic"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - source .industrial_ci/travis.sh
