opcua_communication: ros_server.OpcUaROSTopic Class Reference
ros_server.OpcUaROSTopic Class Reference
Public Member Functions
def __init__
def message_callback
def update_value
Public Attributes
type_name
name
message_class
message_instance
Private Member Functions
def _recursive_create_items
def _extract_array_info
def _create_node_with_type
def _recursive_delete_widget_items
Private Attributes
_nodes
_subscriber
Detailed Description
Definition at line 15 of file ros_server.py.
Constructor & Destructor Documentation
def ros_server.OpcUaROSTopic.__init__ (self, parent, idx, topic_name, topic_type)
Definition at line 17 of file ros_server.py.
Member Function Documentation
def ros_server.OpcUaROSTopic._create_node_with_type (self, parent, idx, topic_name, topic_text, type_name, array_size) private
Definition at line 78 of file ros_server.py.
Referenced by ros_server.OpcUaROSTopic._recursive_create_items().
def ros_server.OpcUaROSTopic._extract_array_info (self, type_str) private
Definition at line 66 of file ros_server.py.
Referenced by ros_server.OpcUaROSTopic._recursive_create_items(), and ros_server.OpcUaROSTopic.update_value().
def ros_server.OpcUaROSTopic._recursive_create_items (self, parent, idx, topic_name, type_name, message) private
Definition at line 36 of file ros_server.py.
References ros_server.OpcUaROSTopic._create_node_with_type(), ros_server.OpcUaROSTopic._extract_array_info(), ros_server.OpcUaROSTopic._nodes, and ros_server.OpcUaROSTopic._recursive_create_items().
Referenced by ros_server.OpcUaROSTopic._recursive_create_items(), and ros_server.OpcUaROSTopic.update_value().
def ros_server.OpcUaROSTopic._recursive_delete_widget_items (self, item) private
Definition at line 149 of file ros_server.py.
def ros_server.OpcUaROSTopic.message_callback (self, message)
Definition at line 122 of file ros_server.py.
References ros_server.OpcUaROSTopic.name, and ros_server.OpcUaROSTopic.update_value().
def ros_server.OpcUaROSTopic.update_value (self, topic_name, message)
Definition at line 126 of file ros_server.py.
References ros_server.OpcUaROSTopic._extract_array_info(), ros_server.OpcUaROSTopic._nodes, ros_server.OpcUaROSTopic._recursive_create_items(), and ros_server.OpcUaROSTopic.update_value().
Referenced by ros_server.OpcUaROSTopic.message_callback(), and ros_server.OpcUaROSTopic.update_value().
Member Data Documentation
ros_server.OpcUaROSTopic._nodes private
Definition at line 22 of file ros_server.py.
Referenced by ros_server.OpcUaROSTopic._recursive_create_items(), and ros_server.OpcUaROSTopic.update_value().
ros_server.OpcUaROSTopic._subscriber private
Definition at line 34 of file ros_server.py.
ros_server.OpcUaROSTopic.message_class
Definition at line 24 of file ros_server.py.
ros_server.OpcUaROSTopic.message_instance
Definition at line 27 of file ros_server.py.
ros_server.OpcUaROSTopic.name
Definition at line 20 of file ros_server.py.
Referenced by ros_server.OpcUaROSTopic.message_callback().
ros_server.OpcUaROSTopic.type_name
Definition at line 19 of file ros_server.py.
The documentation for this class was generated from the following file:
opcua_impl_freeopcua/scripts/ros_server.py