opcua_communication: opcua_impl_freeopcua/src/opcua_client.cpp File Reference
opcua_client.cpp File Reference
This file implements OpcUa client based on FreeOpcUa implementation.
#include <ros/ros.h>
#include <opcua_helpers.h>
#include "opcua_msgs/Address.h"
#include "opcua_msgs/TypeValue.h"
#include "opcua_srvs/CallMethod.h"
#include "opcua_srvs/Connect.h"
#include "opcua_srvs/Disconnect.h"
#include "opcua_srvs/ListNode.h"
#include "opcua_srvs/Read.h"
#include "opcua_srvs/Subscribe.h"
#include "opcua_srvs/Write.h"
#include "opcua_srvs/Unsubscribe.h"
#include <opc/ua/client/client.h>
#include <opc/ua/subscription.h>
Classes
class SubClient
Subscription client class handles subscription callbacks.
Functions
bool connect (opcua_srvs::Connect::Request &req, opcua_srvs::Connect::Response &res)
bool disconnect (opcua_srvs::Disconnect::Request &req, opcua_srvs::Disconnect::Response &res)
bool list_node (opcua_srvs::ListNode::Request &req, opcua_srvs::ListNode::Response &res)
bool call_method (opcua_srvs::CallMethod::Request &req, opcua_srvs::CallMethod::Response &res)
bool read (opcua_srvs::Read::Request &req, opcua_srvs::Read::Response &res)
bool write (opcua_srvs::Write::Request &req, opcua_srvs::Write::Response &res)
bool subscribe (opcua_srvs::Subscribe::Request &req, opcua_srvs::Subscribe::Response &res)
bool unsubscribe (opcua_srvs::Unsubscribe::Request &req, opcua_srvs::Unsubscribe::Response &res)
int main (int argc, char **argv)
Variables
OpcUa::UaClient _client
Client variable.
std::map< std::string,
std::unique_ptr
< OpcUa::Subscription > > _subscriptions
Subscription list.
std::map< std::string,
ros::Publisher > _callback_publishers
Callback publishers list.
std::map< std::string, uint32_t > _subscription_handles
List of subscription handles.
SubClient _sclt
Subscription client store.
Detailed Description
This file implements OpcUa client based on FreeOpcUa implementation.
Author
Denis Štogl
Copyright
Copyright 2015 SkillPro Consortium
         This file is part of SkillPro-Framework.
         SkillPro-Framework is free software: you can redistribute it and/or modify
         it under the terms of the GNU Lesser General Public License as published by
         the Free Software Foundation, either version 3 of the License, or
         (at your option) any later version.
         SkillPro-Framework is distributed in the hope that it will be useful,
         but WITHOUT ANY WARRANTY; without even the implied warranty of
         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         GNU Lesser General Public License for more details.
         You should have received a copy of the GNU Lesser General Public License
         along with SkillPro-Framework. If not, see <http://www.gnu.org/licenses/>.
Todo:
Would be cool to have dignostic topic to write subscirptions and stuff
Definition in file opcua_client.cpp.
Function Documentation
bool call_method (opcua_srvs::CallMethod::Request & req, opcua_srvs::CallMethod::Response & res)
Definition at line 178 of file opcua_client.cpp.
References _client, convertAddressToNodeID(), convertTypeValueToVariant(), and convertVariantToTypeValue().
Referenced by main().
bool connect (opcua_srvs::Connect::Request & req, opcua_srvs::Connect::Response & res)
ROS-service call: Connect. Connects to OpcUa server.
Parameters
req service request
res service response
Returns
True, if service execution broken than False.
Definition at line 87 of file opcua_client.cpp.
References _client.
Referenced by main().
bool disconnect (opcua_srvs::Disconnect::Request & req, opcua_srvs::Disconnect::Response & res)
ROS-service call: Disconnect. Disconnects from OpcUa server.
Parameters
req service request
res service response
Returns
True, if service execution broken than False.
Definition at line 119 of file opcua_client.cpp.
References _client.
Referenced by main().
bool list_node (opcua_srvs::ListNode::Request & req, opcua_srvs::ListNode::Response & res)
ROS-service call: ListNode. Gets list of Node children from OpcUa server.
Parameters
req service request
res service response
Returns
True, if service execution broken than False.
Definition at line 148 of file opcua_client.cpp.
References _client, convertAddressToNodeID(), and convertNodeIDToAddress().
Referenced by main().
int main (int argc, char ** argv)
Start function of ROS-Node with default name 'opcua_client_node'
Parameters
argc number of command line arguments
argv command line arguments
Returns
0 if programs ends successfully.
Definition at line 404 of file opcua_client.cpp.
References _client, call_method(), connect(), disconnect(), list_node(), read(), subscribe(), unsubscribe(), and write().
bool read (opcua_srvs::Read::Request & req, opcua_srvs::Read::Response & res)
ROS-service call: Read. Reads value from OpcUa server.
Parameters
req service request
res service response
Returns
True, if service execution broken than False.
Definition at line 224 of file opcua_client.cpp.
References _client, convertAddressToNodeID(), and convertVariantToTypeValue().
Referenced by main().
bool subscribe (opcua_srvs::Subscribe::Request & req, opcua_srvs::Subscribe::Response & res)
ROS-service call: Subscribe. Subscribe to DataChange of Node on OpcUa server.
Parameters
req service request
res service response
Returns
True, if service execution broken than False.
Todo:
can subscribe on only one node
Definition at line 313 of file opcua_client.cpp.
References _callback_publishers, _client, _subscription_handles, _subscriptions, and convertAddressToNodeID().
Referenced by main().
bool unsubscribe (opcua_srvs::Unsubscribe::Request & req, opcua_srvs::Unsubscribe::Response & res)
ROS-service call: Unsubscribe. Unsubscribe from Node on OpcUa server.
Parameters
req service request
res service response
Returns
True, if service execution broken than False.
Definition at line 357 of file opcua_client.cpp.
References _callback_publishers, _client, _subscription_handles, _subscriptions, and convertAddressToNodeID().
Referenced by main().
bool write (opcua_srvs::Write::Request & req, opcua_srvs::Write::Response & res)
ROS-service call: Write. Writes value to OpcUa server.
Parameters
req service request
res service response
Returns
True, if service execution broken than False.
Definition at line 266 of file opcua_client.cpp.
References _client, convertAddressToNodeID(), and convertTypeValueToVariant().
Referenced by main().
Variable Documentation
std::map<std::string, ros::Publisher> _callback_publishers
Callback publishers list.
Key is OpcUa string node identifier and value ROS publisher
Definition at line 52 of file opcua_client.cpp.
Referenced by SubClient::DataChange(), subscribe(), and unsubscribe().
OpcUa::UaClient _client
Client variable.
Definition at line 46 of file opcua_client.cpp.
Referenced by call_method(), connect(), disconnect(), list_node(), main(), read(), subscribe(), unsubscribe(), and write().
SubClient _sclt
Subscription client store.
Todo:
Need checking for multiple subscriptions
Definition at line 79 of file opcua_client.cpp.
std::map<std::string, uint32_t> _subscription_handles
List of subscription handles.
Key is OpcUa string node identifier and value is node handle. This is needed for deteting of subscriptions
Definition at line 55 of file opcua_client.cpp.
Referenced by subscribe(), and unsubscribe().
std::map<std::string, std::unique_ptr<OpcUa::Subscription> > _subscriptions
Subscription list.
Key is OpcUa string node identifier and value subscription reference.
Definition at line 49 of file opcua_client.cpp.
Referenced by subscribe(), and unsubscribe().