opcua_communication: opcua_impl_freeopcua/include/opcua_helpers.h File Reference
opcua_helpers.h File Reference
This file contains helper functions for ROS implementation of OpcUa client.
#include "opcua_msgs/Address.h"
#include "opcua_msgs/TypeValue.h"
#include <opc/ua/node.h>
#include <opc/ua/protocol/string_utils.h>
Functions
OpcUa::NodeID convertAddressToNodeID (const opcua_msgs::Address address)
opcua_msgs::Address convertNodeIDToAddress (const OpcUa::NodeID nodeID)
opcua_msgs::TypeValue convertVariantToTypeValue (const OpcUa::Variant &variant)
OpcUa::Variant convertTypeValueToVariant (opcua_msgs::TypeValue &typeValue)
Variables
std::map< int, std::string > _TypeToStringMap
Remapping between ROS types and OpenOpcUa types.
Detailed Description
This file contains helper functions for ROS implementation of OpcUa client.
Author
Denis Štogl
Copyright
Copyright 2015 SkillPro Consortium
         This file is part of SkillPro-Framework.
         SkillPro-Framework is free software: you can redistribute it and/or modify
         it under the terms of the GNU Lesser General Public License as published by
         the Free Software Foundation, either version 3 of the License, or
         (at your option) any later version.
         SkillPro-Framework is distributed in the hope that it will be useful,
         but WITHOUT ANY WARRANTY; without even the implied warranty of
         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         GNU Lesser General Public License for more details.
         You should have received a copy of the GNU Lesser General Public License
         along with SkillPro-Framework. If not, see <http://www.gnu.org/licenses/>.
Definition in file opcua_helpers.h.
Function Documentation
OpcUa::NodeID convertAddressToNodeID (const opcua_msgs::Address address)
This function converts between opcua_msgs::Address data type into OpcUa::NodeID data type.
Parameters
address address to convert.
Returns
NodeID object created from address.
Definition at line 65 of file opcua_helpers.h.
Referenced by call_method(), list_node(), read(), subscribe(), unsubscribe(), and write().
opcua_msgs::Address convertNodeIDToAddress (const OpcUa::NodeID nodeID)
This function converts between OpcUa::NodeID data type into opcua_msgs::Address data type.
Parameters
nodeID nodeId to convert.
Returns
Address object created from nodeID.
Definition at line 87 of file opcua_helpers.h.
Referenced by list_node().
OpcUa::Variant convertTypeValueToVariant (opcua_msgs::TypeValue & typeValue)
This function converts opcua_msgs::TypeValue data type into OpcUa::Variant data type.
Parameters
typeValue TypeValue to be converted
Returns
Variant object created from typeValue
Definition at line 194 of file opcua_helpers.h.
Referenced by call_method(), and write().
opcua_msgs::TypeValue convertVariantToTypeValue (const OpcUa::Variant & variant)
This function converts OpcUa::Variant data type into opcua_msgs::TypeValue data type.
Parameters
variant Variant to be converted.
Returns
TypeValue object created from variant.
Definition at line 140 of file opcua_helpers.h.
References _TypeToStringMap.
Referenced by call_method(), SubClient::DataChange(), and read().
Variable Documentation
std::map<int, std::string> _TypeToStringMap
Initial value:
= {
    {1, "bool"},
    {2, "int8"},
    {3, "uint8"},
    {4, "int16"},
    {5, "uint16"},
    {6, "int32"},
    {7, "uint32"},
    {8, "int64"},
    {9, "uint64"},
    {10, "float32"},
    {11, "float64"},
    {12, "string"},
}
Remapping between ROS types and OpenOpcUa types.
Commented values are not used in current implementation, there don't exist remapping to ROS.
Definition at line 31 of file opcua_helpers.h.
Referenced by convertVariantToTypeValue().