name: CI

on:
  push:
    branches: [ kinetic-devel ]
  pull_request: 
    branches: [ kinetic-devel ]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic, ROS_REPO: main, ADDITIONAL_DEBS: "libxml2-dev libmbedtls-dev"}
          - {ROS_DISTRO: melodic, ROS_REPO: main, ADDITIONAL_DEBS: "libxml2-dev libmbedtls-dev"}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        submodules: 'true'
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
